version: '3.8'
services:
  ghost-dev:
    image: ghost:latest
    ports:
      - "3000:2368"
    volumes:
      - ./data-dev:/var/lib/ghost/content
    environment:
      - NODE_ENV=development
      - database__client=mysql
      - database__connection__host=mysql-dev
      - database__connection__user=root
      - database__connection__password=rootpassword
      - database__connection__database=ghost_dev
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ghost_dev
    volumes:
      - mysql-dev-data:/var/lib/mysql

volumes:
  mysql-dev-data:
