name: Build and Deploy Ghost

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build . -t ghost-project:${{ github.sha }}

      - name: Run Docker Compose
        run: docker-compose up -d
